In [1]:
import numpy

In [2]:
a = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
b = numpy.eye(5)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
c = numpy.zeros((3, 4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
d = numpy.ones((5, 6))
print(d)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [12]:
e = numpy.arange(0, 20, 2)
print(e)

[ 0  2  4  6  8 10 12 14 16 18]


In [15]:
f = e.reshape((3, 4))
print(f)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [17]:
print(a[2, 2])

9


In [19]:
print(a[0, :])

[1 2 3]


In [21]:
print(a[:, 1])

[2 5 8]


In [24]:
print(a[[1, 0], [2, 2]])

[6 3]


In [31]:
g = numpy.array([1, 2, 3])
h = numpy.array([[[1], [2], [3]], [[4], [5], [6]]])

print(g)
print(g.shape)
print(h)
print(h.shape)

[1 2 3]
(3,)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 3, 1)


In [33]:
g = g.T
h = h.T

print(g)
print(g.shape)
print(h)
print(h.shape)

[1 2 3]
(3,)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 3, 1)


In [35]:
i = numpy.array([[1, 2], [3, 4]])
j = numpy.array([[2, 3], [4, 5]])

ij = numpy.dot(i, j)
print(ij)

ji = i.dot(j)
print(ji)

[[10 13]
 [22 29]]
[[10 13]
 [22 29]]


In [37]:
iijj = i * j
print(iijj)

[[ 2  6]
 [12 20]]


In [39]:
k = numpy.array([[1, 2], [3, 4]])

l = numpy.transpose(k)
print(l)
m = k.T
print(m)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [61]:
n = numpy.array([[4, 2, 4], [2, 1, 2], [7, 12, 9]])
print(n)

o = numpy.det(n)
print(o)

[[ 4  2  4]
 [ 2  1  2]
 [ 7 12  9]]


AttributeError: module 'numpy' has no attribute 'det'

In [46]:
p = numpy.linalg.matrix_rank(n)
print(p)

2


In [51]:
r = numpy.array([[3, 1], [1, 2]])
q = numpy.array([9, 8])

s = numpy.linalg.solve(r, q)
print(s)
print(r.dot(s))

[2. 3.]
[9. 8.]


In [54]:
t = numpy.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=numpy.float32)
u = numpy.linalg.inv(t)

print(t)
print(u)
print(t.dot(u))

[[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
[[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
v = numpy.array([[-1, -6], [2, 6]])
w, x = numpy.linalg.eig(v)

print(v)
print(w)
print(x)


[[-1 -6]
 [ 2  6]]
[2. 3.]
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


In [59]:
y = numpy.array([[1, 1], [1, 2]])
z = y.T

print(y)
print(z)

[[1 1]
 [1 2]]
[[1 1]
 [1 2]]


In [60]:
a = numpy.eye(4, 5)
print(a[[0, 3], [1, 3]])

[0. 1.]
