In [3]:
import numpy


In [7]:
a = numpy.array([1, 2, 3])
print(a)

[1 2 3]


In [9]:
b = numpy.array([1, 2, 3], dtype=float)
print(b)

[1. 2. 3.]


In [11]:
print(a.dtype)

int32


In [12]:
print(b.dtype)

float64


In [13]:
c = numpy.arange(start=10, stop=20, step=2)
print(c)

[10 12 14 16 18]


In [14]:
d = numpy.arange(start=0.1, stop=0.5, step=0.1, dtype=float)
print(d)

[0.1 0.2 0.3 0.4]


In [15]:
print(c.ndim)

1


In [17]:
print(d.shape)

(4,)


In [20]:
a = numpy.array([1, 2, 3])
b = numpy.array([6, 5, 4])
k = 2

print(a)
print(b)
print(k)

[1 2 3]
[6 5 4]
2


In [21]:
print(a + b)

[7 7 7]


In [22]:
print(a - b)

[-5 -3 -1]


In [23]:
print(a * b)

[ 6 10 12]


In [24]:
print(a * k)

[2 4 6]


In [25]:
from numpy.linalg import norm

In [26]:
a = numpy.array([1, 2, -3])
print(a)

[ 1  2 -3]


In [27]:
print(norm(a, ord=1))

6.0


In [28]:
print(norm(a, ord=2))

3.7416573867739413


In [29]:
a = numpy.array([1, 2, -3])
b = numpy.array([-4, 3, 8])

print(a)
print(b)

[ 1  2 -3]
[-4  3  8]


In [30]:
print(norm(a - b, ord=1))
print(norm(a - b, ord=2))

17.0
12.12435565298214


In [31]:
a = numpy.array([0, 5, -1])
b = numpy.array([-4, 9, 3])

print(a)
print(b)

[ 0  5 -1]
[-4  9  3]


In [32]:
print(numpy.dot(a, b))

42


In [33]:
print(a.dot(b))

42


In [34]:
cos_angle = numpy.dot(a, b) / norm(a) / norm(b)
print(cos_angle)
print(numpy.arccos(cos_angle))

0.8000362836474323
0.6434406336093618


In [35]:
a = numpy.array([-1, 2, -1])
print(norm(a, ord=1))

4.0


In [36]:
a = numpy.array([1, 2, 3])
b = numpy.array([-3, 1, 1])
print(numpy.dot(a, b))

2
